### ISSUE TITLE
[Feature] Add custom font file upload and search

### ISSUE THREAD

**Issue by Crni39** [notmike101/betterdiscord-google-fonts#2]
tittle tells everything

**Comment by notmike101** [comment]
This plugin was made with the idea of using Google Fonts exclusively (also a test for me to write a useable plugin using Typescript) in order to follow UNIX philosophy. Not sure that allowing fonts from other sources or locally would fall in line with that.

What may be a option in order to stick with UNIX philosophy is creating a new plugin for this functionality. A new plugin can encompass the functionality of this plugin at some level as well with some major improvements, but I'd need to design the plugin in a much better way.

**Comment by Crni39** [comment]
yeah but there are missing fonts, ect i wanted Choco cooky, thats google font but its not on list, and one more thing, when you're in menu, and you type some letter, it will auto scroll to it.

**Comment by notmike101** [comment]
> yeah but there are missing fonts, ect i wanted Choco cooky, thats google font but its not on list, and one more thing, when you're in menu, and you type some letter, it will auto scroll to it.

https://fonts.google.com/?query=choco+cooky

I'm not seeing a font called "Choco Cooky" in Google Fonts.

I'll work on adding a filter to the list though, that does seem like a useful feature.
